### ISSUE TITLE
Possible optional info for README, some bits specific to Heroku

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-rails-examples#1]
I'm happy to work up PRs if desirable (not sure if just adding optional sections to the README would be best?) but I wanted to share a few other bits from a Rails app I have running Falcon on Heroku:

`falcon.rb` preloads the app, disables caching, hooks into an ENV var which should match the CPU count (1 for Standard-1x dynes) and configures for HTTP1 (until they support HTTP2):

```ruby
#!/usr/bin/env -S falcon host

load :rack

hostname = File.basename(__dir__)
port = ENV["PORT"] || 3000

rack hostname do
  append preload "preload.rb"
  cache false
  count ENV.fetch("FALCON_COUNT", 1).to_i
  endpoint Async::HTTP::Endpoint.parse("http://0.0.0.0:#{port}").with(protocol: Async::HTTP::Protocol::HTTP11)
end
```

`preload.rb`:

```ruby
require_relative "config/environment"
```

`Procfile`:
```ruby
web: bundle exec ./falcon.rb
```

**Comment by ioquatix** [comment]
Yeah, I think it would be good to have an integration guide.
